# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sun Jul  3 13:34:56 2016
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1016, 1856)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        Form.setPalette(palette)
        self.text_date = QtGui.QLabel(Form)
        self.text_date.setGeometry(QtCore.QRect(10, 10, 351, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(24)
        self.text_date.setFont(font)
        self.text_date.setObjectName(_fromUtf8("text_date"))
        self.text_time = QtGui.QLabel(Form)
        self.text_time.setGeometry(QtCore.QRect(10, 80, 351, 101))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(48)
        self.text_time.setFont(font)
        self.text_time.setObjectName(_fromUtf8("text_time"))
        self.text_temp = QtGui.QLabel(Form)
        self.text_temp.setGeometry(QtCore.QRect(820, 10, 191, 121))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(48)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.text_temp.setFont(font)
        self.text_temp.setObjectName(_fromUtf8("text_temp"))
        self.text_min_temp = QtGui.QLabel(Form)
        self.text_min_temp.setGeometry(QtCore.QRect(820, 140, 91, 51))
        self.text_min_temp.setObjectName(_fromUtf8("text_min_temp"))
        self.text_max_temp = QtGui.QLabel(Form)
        self.text_max_temp.setGeometry(QtCore.QRect(920, 140, 91, 51))
        self.text_max_temp.setObjectName(_fromUtf8("text_max_temp"))
        self.text_todo = QtGui.QLabel(Form)
        self.text_todo.setGeometry(QtCore.QRect(10, 1460, 351, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(24)
        self.text_todo.setFont(font)
        self.text_todo.setObjectName(_fromUtf8("text_todo"))
        self.text_tasks = QtGui.QTextBrowser(Form)
        self.text_tasks.setGeometry(QtCore.QRect(10, 1530, 331, 311))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(11)
        self.text_tasks.setFont(font)
        self.text_tasks.setObjectName(_fromUtf8("text_tasks"))
        self.text_station = QtGui.QLabel(Form)
        self.text_station.setGeometry(QtCore.QRect(660, 1460, 351, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(24)
        self.text_station.setFont(font)
        self.text_station.setObjectName(_fromUtf8("text_station"))
        self.draw_mvg1 = QtGui.QLabel(Form)
        self.draw_mvg1.setGeometry(QtCore.QRect(660, 1530, 55, 51))
        self.draw_mvg1.setObjectName(_fromUtf8("draw_mvg1"))
        self.text_dest_1 = QtGui.QLabel(Form)
        self.text_dest_1.setGeometry(QtCore.QRect(730, 1530, 211, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(11)
        self.text_dest_1.setFont(font)
        self.text_dest_1.setObjectName(_fromUtf8("text_dest_1"))
        self.text_mvg_time1 = QtGui.QLabel(Form)
        self.text_mvg_time1.setGeometry(QtCore.QRect(950, 1530, 55, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(11)
        self.text_mvg_time1.setFont(font)
        self.text_mvg_time1.setObjectName(_fromUtf8("text_mvg_time1"))
        self.draw_mvg2 = QtGui.QLabel(Form)
        self.draw_mvg2.setGeometry(QtCore.QRect(660, 1590, 55, 51))
        self.draw_mvg2.setObjectName(_fromUtf8("draw_mvg2"))
        self.draw_mvg3 = QtGui.QLabel(Form)
        self.draw_mvg3.setGeometry(QtCore.QRect(660, 1650, 55, 51))
        self.draw_mvg3.setObjectName(_fromUtf8("draw_mvg3"))
        self.draw_mvg4 = QtGui.QLabel(Form)
        self.draw_mvg4.setGeometry(QtCore.QRect(660, 1710, 55, 51))
        self.draw_mvg4.setObjectName(_fromUtf8("draw_mvg4"))
        self.draw_nvg5 = QtGui.QLabel(Form)
        self.draw_nvg5.setGeometry(QtCore.QRect(660, 1770, 55, 51))
        self.draw_nvg5.setObjectName(_fromUtf8("draw_nvg5"))
        self.text_dest2 = QtGui.QLabel(Form)
        self.text_dest2.setGeometry(QtCore.QRect(730, 1590, 211, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(11)
        self.text_dest2.setFont(font)
        self.text_dest2.setObjectName(_fromUtf8("text_dest2"))
        self.text_dest3 = QtGui.QLabel(Form)
        self.text_dest3.setGeometry(QtCore.QRect(730, 1650, 211, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(11)
        self.text_dest3.setFont(font)
        self.text_dest3.setObjectName(_fromUtf8("text_dest3"))
        self.text_dest4 = QtGui.QLabel(Form)
        self.text_dest4.setGeometry(QtCore.QRect(730, 1710, 211, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(11)
        self.text_dest4.setFont(font)
        self.text_dest4.setObjectName(_fromUtf8("text_dest4"))
        self.text_dest5 = QtGui.QLabel(Form)
        self.text_dest5.setGeometry(QtCore.QRect(730, 1770, 211, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(11)
        self.text_dest5.setFont(font)
        self.text_dest5.setObjectName(_fromUtf8("text_dest5"))
        self.text_mvg_time2 = QtGui.QLabel(Form)
        self.text_mvg_time2.setGeometry(QtCore.QRect(950, 1590, 55, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(11)
        self.text_mvg_time2.setFont(font)
        self.text_mvg_time2.setObjectName(_fromUtf8("text_mvg_time2"))
        self.text_mvg_time3 = QtGui.QLabel(Form)
        self.text_mvg_time3.setGeometry(QtCore.QRect(950, 1650, 55, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(11)
        self.text_mvg_time3.setFont(font)
        self.text_mvg_time3.setObjectName(_fromUtf8("text_mvg_time3"))
        self.text_mvg_time4 = QtGui.QLabel(Form)
        self.text_mvg_time4.setGeometry(QtCore.QRect(950, 1710, 55, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(11)
        self.text_mvg_time4.setFont(font)
        self.text_mvg_time4.setObjectName(_fromUtf8("text_mvg_time4"))
        self.text_mvg_time5 = QtGui.QLabel(Form)
        self.text_mvg_time5.setGeometry(QtCore.QRect(950, 1770, 55, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(11)
        self.text_mvg_time5.setFont(font)
        self.text_mvg_time5.setObjectName(_fromUtf8("text_mvg_time5"))
        self.draw_weather_logo = QtGui.QLabel(Form)
        self.draw_weather_logo.setGeometry(QtCore.QRect(630, 10, 181, 181))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(48)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.draw_weather_logo.setFont(font)
        self.draw_weather_logo.setObjectName(_fromUtf8("draw_weather_logo"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.text_date.setText(_translate("Form", "30.06.2016", None))
        self.text_time.setText(_translate("Form", "13:51", None))
        self.text_temp.setText(_translate("Form", "20°", None))
        self.text_min_temp.setText(_translate("Form", "TextLabel", None))
        self.text_max_temp.setText(_translate("Form", "TextLabel", None))
        self.text_todo.setText(_translate("Form", "Today\'s Tasks:", None))
        self.text_station.setText(_translate("Form", "Parzivalplatz", None))
        self.draw_mvg1.setText(_translate("Form", "TextLabel", None))
        self.text_dest_1.setText(_translate("Form", "TextLabel", None))
        self.text_mvg_time1.setText(_translate("Form", "1 min", None))
        self.draw_mvg2.setText(_translate("Form", "TextLabel", None))
        self.draw_mvg3.setText(_translate("Form", "TextLabel", None))
        self.draw_mvg4.setText(_translate("Form", "TextLabel", None))
        self.draw_nvg5.setText(_translate("Form", "TextLabel", None))
        self.text_dest2.setText(_translate("Form", "TextLabel", None))
        self.text_dest3.setText(_translate("Form", "TextLabel", None))
        self.text_dest4.setText(_translate("Form", "TextLabel", None))
        self.text_dest5.setText(_translate("Form", "TextLabel", None))
        self.text_mvg_time2.setText(_translate("Form", "1 min", None))
        self.text_mvg_time3.setText(_translate("Form", "1 min", None))
        self.text_mvg_time4.setText(_translate("Form", "1 min", None))
        self.text_mvg_time5.setText(_translate("Form", "1 min", None))
        self.draw_weather_logo.setText(_translate("Form", "20°", None))

